
name: inherit_called
on:
  workflow_call:
jobs:
  called:
    runs-on: ms-nick
    steps:
      - run: echo ${{ secrets.REPO_SECRET }}
      - run: echo ${{ secrets.ORG_SECRET }}
  env_job:
    runs-on: ms-nick
    environment: production
    steps:
      - run: echo ${{ secrets.PROD_SECRET }}
